import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    name: 'jsdom',
    environment: 'jsdom',
    setupFiles: ['src/tests/setupFile.ts'],
    include: ['src/**/*.{test,spec}.{ts,tsx}'],
    exclude: ['**/*.config.{js,mjs,ts}'],
    coverage: {
      provider: 'v8',
      enabled: true,
      thresholds: {
        statements: 80,
        branches: 50,
        functions: 50,
        lines: 50,
      },
      include: ['src/**/*.{js,jsx,ts,tsx}'],
      exclude: [
        '.next/',
        'eslint.config.mjs',
        'next.config.ts',
        'node_modules/',
        'postcss.config.mjs',
        'vitest.config.mts',
        'src/app/api/**',
        'src/app/**/*.{js,jsx,ts,tsx}',
        'src/components/api',
        'src/components/contexts',
        'src/components/copy-button.tsx',
        'src/components/history/**',
        'src/components/history-component.tsx',
        'src/components/language-toggler.tsx',
        'src/components/loader.tsx',
        'src/components/main-sections/**',
        'src/components/rest-client',
        'src/components/theme-toggler.tsx',
        'src/components/ui/**',
        'src/components/**/types.ts',
        'src/firebase.ts',
        'src/firebaseAdmin.ts',
        'src/lib/schemas/**',
        'src/lib/stores/**',
        'src/types/**',
        'src/utils/**',
        'src/index.{js,jsx,ts,tsx}',
        'src/language-toggler.tsx',
        'src/main.tsx',
        'src/middleware.ts',
        'src/setupTests.{js,ts}',
        'src/tests/setupFile.ts',
        'src/**/*.spec.{js,jsx,ts,tsx}',
        'src/**/*.test.{js,jsx,ts,tsx}',
        'src/**/*.d.ts',
        'src/**/validate-form.ts',
        '**/*.d.ts',
      ],
    },
  },
});
